services:
  # Development service
  app-dev:
    container_name: nextjs-prescription-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "13204:3000"
    networks:
      - my-shared-proxy-net
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
      - ./uploads:/app/public/uploads
    environment:
      - NODE_ENV=development
        # Enable polling for file watching (required for hot reload in Docker)
      - WATCHPACK_POLLING=${WATCHPACK_POLLING:-true}
      - CHOKIDAR_USEPOLLING=${CHOKIDAR_USEPOLLING:-true}
    # command: pnpm run dev
    profiles:
      - dev

  # Production service
  app-prod:
    image: lambki/nextjs-prescription:latest
    container_name: nextjs-prescription
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "13204:3000"
    networks:
      - my-shared-proxy-net
    volumes:
      - uploads_data:/app/public/uploads
    environment:
      NODE_ENV: ${NODE_ENV:-production}
    restart: unless-stopped
    profiles:
      - prod

volumes:
  uploads_data:

networks:
  my-shared-proxy-net:
    external: true

